"use client";

import { FormEvent, use, useEffect, useRef, useState } from "react";
import { AlertTriangle, ArrowLeft, Send } from "lucide-react";
import { useAuthStore } from "@/store/useAuthStore";

type Message = { sender: "assistant" | "patient"; text: string };
export default function VisitHelp({ params }: { params: Promise<{ id: string }> }) {
  const id = use(params).id; const { token } = useAuthStore(); const socket = useRef<WebSocket | null>(null); const [messages, setMessages] = useState<Message[]>([{ sender: "assistant", text: "I can help explain the care plan your doctor approved for this visit. I cannot diagnose new symptoms or change your treatment." }]); const [text, setText] = useState(""); const [connected, setConnected] = useState(false); const [error, setError] = useState(""); const [urgent, setUrgent] = useState(false);
  useEffect(() => { if (!token) return; const value = new WebSocket(`ws://localhost:8100/api/v1/appointments/${id}/companion/chat`); socket.current = value; value.onopen = () => { setConnected(true); value.send(JSON.stringify({ appointment_id: id, token })); }; value.onmessage = (event) => { try { const data = JSON.parse(event.data); if (data.error) setError(data.error); if (data.response) setMessages((current) => [...current, { sender: "assistant", text: data.response }]); if (data.escalation_triggered) setUrgent(true); } catch { setError("We could not read the reply. Please try again."); } }; value.onerror = () => setError("Health Help is unavailable right now. Please try again later."); value.onclose = () => setConnected(false); return () => value.close(); }, [id, token]);
  const send = (event: FormEvent) => { event.preventDefault(); if (!text.trim() || socket.current?.readyState !== WebSocket.OPEN) return; socket.current.send(JSON.stringify({ message: text.trim() })); setMessages((current) => [...current, { sender: "patient", text: text.trim() }]); setText(""); };
  return <main className="min-h-screen bg-slate-50 p-4 sm:p-6"><section className="mx-auto max-w-3xl"><a href="/?tab=appointments" className="inline-flex items-center gap-2 text-sm font-semibold text-slate-600 hover:text-teal-700"><ArrowLeft className="h-4 w-4" />Back to appointments</a><div className="mt-5 overflow-hidden rounded-3xl border border-slate-200 bg-white"><header className="border-b border-slate-100 p-5 sm:p-6"><div className="flex items-center justify-between gap-4"><div><h1 className="text-xl font-bold">Visit help</h1><p className="mt-1 text-sm text-slate-600">Questions about your doctor-approved visit plan.</p></div><span className={`rounded-full px-3 py-1 text-xs font-bold ${connected ? "bg-teal-50 text-teal-800" : "bg-slate-100 text-slate-600"}`}>{connected ? "Connected" : "Unavailable"}</span></div></header><div className="border-b border-slate-100 bg-amber-50 p-4 text-sm text-amber-900"><strong>Not for emergencies.</strong> If you have severe or worsening symptoms, call 112 or seek urgent medical care.</div>{urgent && <div className="m-4 flex gap-3 rounded-xl bg-rose-50 p-4 text-sm text-rose-800"><AlertTriangle className="h-5 w-5 shrink-0" />Your message may need urgent medical attention. Please contact emergency services or your doctor now.</div>}{error && <p className="m-4 rounded-xl bg-rose-50 p-3 text-sm text-rose-700">{error}</p>}<div className="min-h-80 space-y-3 p-5 sm:p-6">{messages.map((message, index) => <p key={index} className={`max-w-[85%] rounded-2xl px-4 py-3 text-sm leading-6 ${message.sender === "patient" ? "ml-auto bg-teal-600 text-white" : "bg-slate-100 text-slate-700"}`}>{message.text}</p>)}</div><form onSubmit={send} className="flex gap-3 border-t border-slate-100 p-4"><input value={text} onChange={(event) => setText(event.target.value)} disabled={!connected || urgent} placeholder={connected ? "Ask about your visit plan" : "Visit help is unavailable"} className="min-w-0 flex-1 rounded-xl border border-slate-300 px-3 py-3 text-sm outline-none focus:border-teal-600" /><button disabled={!connected || !text.trim() || urgent} aria-label="Send message" className="rounded-xl bg-teal-600 p-3 text-white disabled:opacity-50"><Send className="h-5 w-5" /></button></form></div></section></main>;
}
