"use client";

import { useMemo, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { CalendarDays, FilePenLine, Video } from "lucide-react";
import PortalShell from "@/components/PortalShell";
import { useAuthStore } from "@/store/useAuthStore";

type Appointment = { id: string; patient_id: string; appointment_time: string; status: string; consult_type: string; reason_for_visit: string; clinical_note?: { status: string } | null };
const start = (item: Appointment) => new Date(item.appointment_time); const status = (item: Appointment) => item.status.toLowerCase();
export default function DoctorDashboard() {
  const { token, user } = useAuthStore(); const [filter, setFilter] = useState<"all" | "review" | "completed">("all"); const [search, setSearch] = useState("");
  const { data: appointments = [], isLoading, isError, refetch } = useQuery<Appointment[]>({ queryKey: ["doctor-appointments", user?.id], enabled: Boolean(token && user?.id), queryFn: async () => { const response = await fetch(`http://localhost:8100/api/v1/appointments?doctor_id=${user!.id}`, { headers: { Authorization: `Bearer ${token}` } }); if (!response.ok) throw new Error("Unable to load appointments"); return response.json(); } });
  const today = new Date().toDateString(); const todayVisits = appointments.filter((item) => start(item).toDateString() === today); const reviewCount = appointments.filter((item) => item.clinical_note?.status === "draft").length;
  const visible = useMemo(() => appointments.filter((item) => { if (filter === "review" && item.clinical_note?.status !== "draft") return false; if (filter === "completed" && status(item) !== "completed") return false; return !search || item.reason_for_visit.toLowerCase().includes(search.toLowerCase()); }).sort((a, b) => start(a).getTime() - start(b).getTime()), [appointments, filter, search]);
  if (user?.role !== "Doctor") return null;
  return <PortalShell doctor title="Appointments" subtitle="Your clinic schedule and notes"><div className="p-4 sm:p-6 lg:p-8"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><h1 className="text-2xl font-bold">Hello, Dr. {user.name.replace(/^Dr\.\s*/i, "")}</h1><p className="mt-1 text-sm text-slate-600">See today’s visits and finish notes that need your review.</p></div></div><div className="mt-6 grid gap-4 sm:grid-cols-2"><Metric label="Today’s visits" value={todayVisits.length} detail={todayVisits.length ? "Based on appointments scheduled for today" : "No visits scheduled today"} icon={<CalendarDays className="h-5 w-5" />} /><Metric label="Notes to review" value={reviewCount} detail={reviewCount ? "Draft notes need your signature" : "No draft notes to review"} icon={<FilePenLine className="h-5 w-5" />} /></div><section className="mt-7 rounded-2xl border border-slate-200 bg-white p-4 sm:p-6"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><h2 className="text-lg font-bold">All appointments</h2><p className="mt-1 text-sm text-slate-600">Only real appointments are shown here.</p></div><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search by visit reason" className="rounded-xl border border-slate-300 px-3 py-2.5 text-sm outline-none focus:border-teal-600" /></div><div className="mt-5 flex gap-2 overflow-x-auto"><Filter active={filter === "all"} onClick={() => setFilter("all")}>All visits</Filter><Filter active={filter === "review"} onClick={() => setFilter("review")}>Notes to review</Filter><Filter active={filter === "completed"} onClick={() => setFilter("completed")}>Completed</Filter></div>{isLoading ? <p className="py-10 text-center text-sm text-slate-500">Loading appointments…</p> : isError ? <p className="mt-5 rounded-xl bg-rose-50 p-4 text-sm text-rose-700">We could not load appointments. <button onClick={() => refetch()} className="font-bold underline">Try again</button></p> : visible.length === 0 ? <p className="mt-5 rounded-xl border border-dashed border-slate-300 p-6 text-sm text-slate-600">No appointments match this view.</p> : <div className="mt-5 grid gap-3">{visible.map((item) => <AppointmentRow key={item.id} item={item} />)}</div>}</section></div></PortalShell>;
}
function Metric({ label, value, detail, icon }: { label: string; value: number; detail: string; icon: React.ReactNode }) { return <div className="rounded-2xl border border-slate-200 bg-white p-5"><span className="grid h-10 w-10 place-items-center rounded-xl bg-teal-50 text-teal-700">{icon}</span><p className="mt-4 text-sm font-semibold text-slate-600">{label}</p><p className="mt-1 text-3xl font-bold">{value}</p><p className="mt-2 text-xs text-slate-500">{detail}</p></div>; }
function Filter({ active, onClick, children }: { active: boolean; onClick: () => void; children: React.ReactNode }) { return <button onClick={onClick} className={`shrink-0 rounded-xl px-3 py-2 text-sm font-semibold ${active ? "bg-teal-600 text-white" : "bg-slate-100 text-slate-600 hover:bg-slate-200"}`}>{children}</button>; }
function AppointmentRow({ item }: { item: Appointment }) { const note = item.clinical_note?.status; const canJoin = item.consult_type === "telehealth" && !["completed", "cancelled"].includes(status(item)); return <article className="flex flex-col gap-4 rounded-xl border border-slate-200 p-4 lg:flex-row lg:items-center lg:justify-between"><div><p className="font-semibold text-slate-900">{item.reason_for_visit || "Appointment"}</p><p className="mt-1 text-sm text-slate-600">{start(item).toLocaleString("en-IN", { dateStyle: "medium", timeStyle: "short" })} · {item.consult_type === "telehealth" ? "Video visit" : "Clinic visit"}</p><p className="mt-2 text-xs font-semibold capitalize text-slate-500">{status(item)}{note ? ` · Note ${note}` : ""}</p></div><div className="flex flex-wrap gap-2">{canJoin && <a href={`/doctor/appointments/${item.id}/room`} className="inline-flex items-center gap-2 rounded-xl bg-teal-600 px-3 py-2 text-sm font-bold text-white"><Video className="h-4 w-4" />Join visit</a>}<a href={`/doctor/appointments/${item.id}/scribe`} className="rounded-xl border border-slate-300 px-3 py-2 text-sm font-bold text-slate-700 hover:bg-slate-50">{note === "draft" ? "Review note" : "Open note"}</a></div></article>; }
