"use client";

import { useState } from "react";
import { CheckCircle2, X } from "lucide-react";
import { useAuthStore } from "@/store/useAuthStore";

type Props = { doctorId: string; doctorName: string; specialty: string; selectedSlotTime?: string; onClose: () => void; onSuccess: () => void };
export default function BookingWizard({ doctorId, doctorName, specialty, selectedSlotTime, onClose, onSuccess }: Props) {
  const { token } = useAuthStore();
  const [visitType, setVisitType] = useState<"in_person" | "telehealth">("in_person"); const [reason, setReason] = useState(""); const [step, setStep] = useState<"details" | "confirm" | "done">("details"); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  const slotText = selectedSlotTime ? new Date(selectedSlotTime).toLocaleString("en-IN", { dateStyle: "full", timeStyle: "short" }) : "No time selected";
  const next = () => { if (!reason.trim()) return setError("Please tell the doctor briefly why you need this visit."); if (!selectedSlotTime) return setError("Please choose an available time before booking."); setError(""); setStep("confirm"); };
  const confirm = async () => { if (!selectedSlotTime) return; setSaving(true); setError(""); try { const response = await fetch("http://localhost:8100/api/v1/appointments", { method: "POST", headers: { "Content-Type": "application/json", Authorization: `Bearer ${token}` }, body: JSON.stringify({ doctor_id: doctorId, appointment_time: selectedSlotTime, consult_type: visitType, reason_for_visit: reason.trim() }) }); const body = await response.json(); if (!response.ok) throw new Error(body.detail || "This time is no longer available. Please choose another one."); setStep("done"); } catch (err) { setError(err instanceof Error ? err.message : "We could not book this visit. Please try again."); } finally { setSaving(false); } };
  return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-900/50 p-4" role="dialog" aria-modal="true" aria-label="Book appointment"><div className="w-full max-w-lg rounded-3xl bg-white p-6 shadow-2xl sm:p-8"><div className="flex items-start justify-between gap-4"><div><p className="text-sm font-semibold text-teal-700">Book appointment</p><h2 className="mt-1 text-xl font-bold">{doctorName}</h2><p className="mt-1 text-sm text-slate-600">{specialty}</p></div>{step !== "done" && <button onClick={onClose} aria-label="Close booking" className="rounded-lg p-2 text-slate-500 hover:bg-slate-100"><X className="h-5 w-5" /></button>}</div>{error && <p className="mt-5 rounded-xl bg-rose-50 p-3 text-sm text-rose-700">{error}</p>}
    {step === "details" && <div className="mt-6 space-y-5"><div className="rounded-xl bg-slate-50 p-4"><p className="text-xs font-bold uppercase tracking-wide text-slate-500">Selected time</p><p className="mt-1 font-semibold text-slate-900">{slotText}</p></div><fieldset><legend className="text-sm font-bold">How would you like to meet?</legend><div className="mt-3 grid grid-cols-2 gap-3"><button onClick={() => setVisitType("in_person")} className={`rounded-xl border p-3 text-sm font-bold ${visitType === "in_person" ? "border-teal-600 bg-teal-50 text-teal-800" : "border-slate-200 text-slate-600"}`}>At clinic</button><button onClick={() => setVisitType("telehealth")} className={`rounded-xl border p-3 text-sm font-bold ${visitType === "telehealth" ? "border-teal-600 bg-teal-50 text-teal-800" : "border-slate-200 text-slate-600"}`}>Video visit</button></div></fieldset><label className="block text-sm font-bold">Reason for visit<textarea value={reason} onChange={(event) => setReason(event.target.value)} rows={4} placeholder="For example: follow-up for headaches" className="mt-2 w-full rounded-xl border border-slate-300 p-3 text-sm font-normal outline-none focus:border-teal-600 focus:ring-2 focus:ring-teal-100" /></label><button onClick={next} className="w-full rounded-xl bg-teal-600 px-4 py-3 text-sm font-bold text-white hover:bg-teal-700">Review booking</button></div>}
    {step === "confirm" && <div className="mt-6 space-y-5"><div className="rounded-2xl border border-teal-100 bg-teal-50 p-5"><h3 className="font-bold text-teal-900">Please check before booking</h3><dl className="mt-4 space-y-3 text-sm"><div><dt className="text-slate-500">Doctor</dt><dd className="font-semibold">{doctorName}, {specialty}</dd></div><div><dt className="text-slate-500">Time</dt><dd className="font-semibold">{slotText}</dd></div><div><dt className="text-slate-500">Visit type</dt><dd className="font-semibold">{visitType === "telehealth" ? "Video visit" : "At clinic"}</dd></div><div><dt className="text-slate-500">Reason</dt><dd className="font-semibold">{reason}</dd></div></dl></div><p className="text-xs leading-5 text-slate-600">Your appointment is created only after you select “Confirm booking.”</p><div className="flex gap-3"><button onClick={() => setStep("details")} disabled={saving} className="flex-1 rounded-xl border border-slate-300 px-4 py-3 text-sm font-bold text-slate-700">Back</button><button onClick={confirm} disabled={saving} className="flex-1 rounded-xl bg-teal-600 px-4 py-3 text-sm font-bold text-white disabled:opacity-60">{saving ? "Booking…" : "Confirm booking"}</button></div></div>}
    {step === "done" && <div className="mt-7 text-center"><CheckCircle2 className="mx-auto h-12 w-12 text-teal-600" /><h3 className="mt-4 text-xl font-bold">Appointment booked</h3><p className="mt-2 text-sm text-slate-600">You can find this appointment in My Appointments.</p><button onClick={onSuccess} className="mt-6 rounded-xl bg-teal-600 px-5 py-3 text-sm font-bold text-white">Done</button></div>}</div></div>;
}
