"use client";

import { useMemo, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { ArrowLeft, CalendarDays, Stethoscope } from "lucide-react";
import BookingWizard from "@/components/BookingWizard";

type Doctor = { id: string; specialty: string; clinic_address?: string; zip_code?: string; user: { name: string } };
export default function DoctorProfileView({ doctorId, onBack }: { doctorId: string; onBack: () => void }) {
  const [date, setDate] = useState(() => new Date().toISOString().slice(0, 10)); const [slot, setSlot] = useState<string | null>(null);
  const { data: doctor, isLoading, isError } = useQuery<Doctor>({ queryKey: ["doctor", doctorId], queryFn: async () => { const response = await fetch(`http://localhost:8100/api/v1/public/doctors/${doctorId}`); if (!response.ok) throw new Error("Unable to load doctor"); return response.json(); } });
  const dates = useMemo(() => Array.from({ length: 7 }, (_, index) => { const value = new Date(); value.setDate(value.getDate() + index); return value.toISOString().slice(0, 10); }), []);
  const { data: slots = [], isLoading: slotsLoading } = useQuery<string[]>({ queryKey: ["availability", doctorId, date], queryFn: async () => { const response = await fetch(`http://localhost:8100/api/v1/public/doctors/${doctorId}/availability?date=${date}`); return response.ok ? response.json() : []; } });
  if (isLoading) return <p className="p-8 text-sm text-slate-500">Loading doctor details…</p>;
  if (isError || !doctor) return <div className="rounded-2xl bg-rose-50 p-6 text-sm text-rose-700">We could not load this doctor. <button onClick={onBack} className="font-bold underline">Back to search</button></div>;
  const dateName = (value: string) => new Date(`${value}T12:00:00`).toLocaleDateString("en-IN", { weekday: "short", day: "numeric", month: "short" });
  return <section className="mx-auto max-w-4xl"><button onClick={onBack} className="inline-flex items-center gap-2 text-sm font-semibold text-slate-600 hover:text-teal-700"><ArrowLeft className="h-4 w-4" />Back to doctors</button><div className="mt-5 rounded-3xl border border-slate-200 bg-white p-6 sm:p-8"><div className="flex gap-4"><span className="grid h-14 w-14 shrink-0 place-items-center rounded-2xl bg-teal-50 text-teal-700"><Stethoscope className="h-7 w-7" /></span><div><h1 className="text-2xl font-bold">{doctor.user.name}</h1><p className="mt-1 font-semibold text-teal-700">{doctor.specialty}</p><p className="mt-3 text-sm leading-6 text-slate-600">Clinic details are confirmed with your appointment.</p></div></div><div className="mt-7 border-t border-slate-100 pt-6"><h2 className="font-bold">Choose a time</h2><p className="mt-1 text-sm text-slate-600">Availability is checked live before you book.</p><div className="mt-4 flex gap-2 overflow-x-auto pb-1">{dates.map((value) => <button key={value} onClick={() => setDate(value)} className={`min-w-24 rounded-xl border px-3 py-2 text-sm font-semibold ${value === date ? "border-teal-600 bg-teal-50 text-teal-800" : "border-slate-200 text-slate-600 hover:bg-slate-50"}`}>{dateName(value)}</button>)}</div>{slotsLoading ? <p className="py-8 text-sm text-slate-500">Checking available times…</p> : slots.length === 0 ? <p className="mt-5 rounded-xl bg-slate-50 p-4 text-sm text-slate-600">No times are available on this date. Please choose another day.</p> : <div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-4">{slots.map((value) => <button key={value} onClick={() => setSlot(value)} aria-label={`Book ${new Date(value).toLocaleString("en-IN", { dateStyle: "full", timeStyle: "short" })}`} className="rounded-xl border border-teal-200 bg-white px-3 py-3 text-sm font-bold text-teal-800 hover:bg-teal-50">{new Date(value).toLocaleTimeString("en-IN", { hour: "numeric", minute: "2-digit" })}</button>)}</div>}</div></div>{slot && <BookingWizard doctorId={doctor.id} doctorName={doctor.user.name} specialty={doctor.specialty} selectedSlotTime={slot} onClose={() => setSlot(null)} onSuccess={() => { setSlot(null); onBack(); }} />}</section>;
}
