"use client";

import { FormEvent, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { CalendarDays, MapPin, Search, Stethoscope } from "lucide-react";

type Doctor = { id: string; specialty: string; clinic_address?: string; zip_code?: string; user: { name: string } };
export default function SearchDashboard({ onSelectDoctor }: { onSelectDoctor: (id: string) => void }) {
  const [specialtyInput, setSpecialtyInput] = useState(""); const [pinInput, setPinInput] = useState(""); const [filters, setFilters] = useState({ specialty: "", pin: "" });
  const { data: doctors = [], isLoading, isError, refetch } = useQuery<Doctor[]>({ queryKey: ["doctors", filters], queryFn: async () => { const params = new URLSearchParams(); if (filters.specialty) params.set("specialty", filters.specialty); if (filters.pin) params.set("zip_code", filters.pin); const response = await fetch(`http://localhost:8100/api/v1/public/doctors?${params}`); if (!response.ok) throw new Error("Unable to load doctors"); return response.json(); } });
  const submit = (event: FormEvent) => { event.preventDefault(); setFilters({ specialty: specialtyInput.trim(), pin: pinInput.trim() }); };
  return <section><div className="max-w-2xl"><h1 className="text-2xl font-bold">Find a doctor</h1><p className="mt-1 text-sm text-slate-600">Search by doctor type or PIN code, then choose a time that works for you.</p></div>
    <form onSubmit={submit} className="mt-6 grid gap-3 rounded-2xl border border-slate-200 bg-white p-4 sm:grid-cols-[1fr_1fr_auto]"><label className="relative"><span className="sr-only">Doctor type</span><Search className="pointer-events-none absolute left-3 top-3 h-5 w-5 text-slate-400" /><input value={specialtyInput} onChange={(event) => setSpecialtyInput(event.target.value)} placeholder="Doctor type, for example skin or heart" className="w-full rounded-xl border border-slate-300 py-3 pl-10 pr-3 text-sm outline-none focus:border-teal-600 focus:ring-2 focus:ring-teal-100" /></label><label className="relative"><span className="sr-only">PIN code</span><MapPin className="pointer-events-none absolute left-3 top-3 h-5 w-5 text-slate-400" /><input inputMode="numeric" value={pinInput} onChange={(event) => setPinInput(event.target.value)} placeholder="PIN code (optional)" className="w-full rounded-xl border border-slate-300 py-3 pl-10 pr-3 text-sm outline-none focus:border-teal-600 focus:ring-2 focus:ring-teal-100" /></label><button className="rounded-xl bg-teal-600 px-5 py-3 text-sm font-bold text-white hover:bg-teal-700">Search</button></form>
    <div className="mt-7"><h2 className="text-lg font-bold">{isLoading ? "Searching…" : `${doctors.length} doctors found`}</h2>{isError ? <div className="mt-4 rounded-2xl bg-rose-50 p-5 text-sm text-rose-700">We could not load doctors. <button onClick={() => refetch()} className="font-bold underline">Try again</button></div> : !isLoading && doctors.length === 0 ? <div className="mt-4 rounded-2xl border border-dashed border-slate-300 bg-white p-6 text-sm text-slate-600">No doctors match this search. Try a different doctor type or clear the PIN code.</div> : <div className="mt-4 grid gap-4 lg:grid-cols-2">{doctors.map((doctor) => <DoctorCard key={doctor.id} doctor={doctor} onSelect={() => onSelectDoctor(doctor.id)} />)}</div>}</div>
  </section>;
}

function DoctorCard({ doctor, onSelect }: { doctor: Doctor; onSelect: () => void }) {
  const today = new Date().toISOString().slice(0, 10);
  const { data: slots = [], isLoading } = useQuery<string[]>({ queryKey: ["next-availability", doctor.id, today], queryFn: async () => { const response = await fetch(`http://localhost:8100/api/v1/public/doctors/${doctor.id}/availability?date=${today}`); return response.ok ? response.json() : []; } });
  const nextSlot = slots[0] ? new Date(slots[0]).toLocaleString("en-IN", { weekday: "short", hour: "numeric", minute: "2-digit" }) : null;
  return <article className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex items-start gap-3"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-teal-50 text-teal-700"><Stethoscope className="h-5 w-5" /></span><div className="min-w-0"><h3 className="font-bold text-slate-900">{doctor.user.name}</h3><p className="mt-0.5 text-sm font-semibold text-teal-700">{doctor.specialty}</p><p className="mt-2 text-sm text-slate-600">Clinic details are shown after you choose a time.</p></div></div><div className="mt-5 flex items-center justify-between gap-3 border-t border-slate-100 pt-4"><p className="text-xs text-slate-600">{isLoading ? "Checking availability…" : nextSlot ? <><CalendarDays className="mr-1 inline h-4 w-4 text-teal-700" />Next: {nextSlot}</> : "Choose a date to see available times"}</p><button onClick={onSelect} className="shrink-0 rounded-xl border border-teal-600 px-3 py-2 text-sm font-bold text-teal-700 hover:bg-teal-50">View times</button></div></article>;
}
