"use client";

import { useEffect, useRef, useState } from "react";
import { Mic, MicOff, PhoneOff, Video, VideoOff } from "lucide-react";
import { useAuthStore } from "@/store/useAuthStore";

type Props = { appointmentId: string; doctor: boolean };
type Appointment = { doctor_id: string; patient_id: string; appointment_time?: string; reason_for_visit?: string };
export default function VideoVisitRoom({ appointmentId, doctor }: Props) {
  const { token, user } = useAuthStore(); const localVideo = useRef<HTMLVideoElement>(null); const remoteVideo = useRef<HTMLVideoElement>(null); const room = useRef<any>(null);
  const [appointment, setAppointment] = useState<Appointment | null>(null); const [peerName, setPeerName] = useState(doctor ? "Patient" : "Doctor"); const [state, setState] = useState<"ready" | "joining" | "joined" | "unavailable">("ready"); const [message, setMessage] = useState(""); const [cameraOn, setCameraOn] = useState(true); const [micOn, setMicOn] = useState(true);
  useEffect(() => { if (!token) return; fetch(`http://localhost:8100/api/v1/appointments/${appointmentId}`, { headers: { Authorization: `Bearer ${token}` } }).then(async (response) => { if (!response.ok) throw new Error("appointment"); return response.json(); }).then(async (value) => { setAppointment(value); const id = doctor ? value.patient_id : value.doctor_id; const endpoint = doctor ? `http://localhost:8100/api/v1/users/${id}` : `http://localhost:8100/api/v1/public/doctors/${id}`; const person = await fetch(endpoint, { headers: doctor ? { Authorization: `Bearer ${token}` } : undefined }).then((response) => response.ok ? response.json() : null); setPeerName(doctor ? person?.name || "Patient" : person?.user?.name || "Doctor"); }).catch(() => { setState("unavailable"); setMessage("We could not connect to this video visit. Please try again later or contact the clinic."); }); return () => room.current?.disconnect(); }, [appointmentId, doctor, token]);
  const join = async () => { if (!token) return; setState("joining"); setMessage(""); try { const response = await fetch("http://localhost:8100/api/v1/telehealth/rooms/token", { method: "POST", headers: { "Content-Type": "application/json", Authorization: `Bearer ${token}` }, body: JSON.stringify({ appointment_id: appointmentId }) }); if (!response.ok) throw new Error("Video service is not available right now. Please try again later or contact the clinic."); const credentials = await response.json(); const { Room, RoomEvent, VideoPresets } = await import("livekit-client"); const nextRoom = new Room({ videoCaptureDefaults: { resolution: VideoPresets.h720.resolution } }); room.current = nextRoom; nextRoom.on(RoomEvent.TrackSubscribed, (track: any) => { if (track.kind === "video" && remoteVideo.current) track.attach(remoteVideo.current); }); await nextRoom.connect("ws://localhost:7980", credentials.token); await nextRoom.localParticipant.enableCameraAndMicrophone(); const publication = nextRoom.localParticipant.getTrackPublication("video" as any); if (publication?.track && localVideo.current) publication.track.attach(localVideo.current); setState("joined"); } catch (error) { room.current?.disconnect(); room.current = null; setState("unavailable"); setMessage(error instanceof Error ? error.message : "Video service is not available right now."); } };
  const toggleCamera = async () => { const next = !cameraOn; await room.current?.localParticipant.setCameraEnabled(next); setCameraOn(next); }; const toggleMic = async () => { const next = !micOn; await room.current?.localParticipant.setMicrophoneEnabled(next); setMicOn(next); }; const leave = () => { room.current?.disconnect(); room.current = null; setState("ready"); };
  const when = appointment?.appointment_time ? new Date(appointment.appointment_time).toLocaleString("en-IN", { dateStyle: "medium", timeStyle: "short" }) : "";
  return <main className="min-h-screen bg-slate-50 p-4 sm:p-6"><section className="mx-auto max-w-6xl"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-sm font-semibold text-teal-700">Video visit</p><h1 className="mt-1 text-2xl font-bold">{doctor ? `Visit with ${peerName}` : `Visit with ${peerName}`}</h1><p className="mt-1 text-sm text-slate-600">{when}{appointment?.reason_for_visit ? ` · ${appointment.reason_for_visit}` : ""}</p></div><a href={doctor ? "/doctor/dashboard" : "/?tab=appointments"} className="rounded-xl border border-slate-300 px-4 py-2 text-sm font-bold text-slate-700">Back to appointments</a></div>{state !== "joined" && <div className="mt-6 max-w-2xl rounded-3xl border border-slate-200 bg-white p-6 sm:p-8"><h2 className="text-xl font-bold">Ready to join?</h2><p className="mt-2 text-sm leading-6 text-slate-600">Your camera and microphone will be requested only when you join. If the video service is unavailable, no simulated visit will be shown.</p>{message && <p className="mt-4 rounded-xl bg-rose-50 p-3 text-sm text-rose-700">{message}</p>}<button onClick={join} disabled={state === "joining" || state === "unavailable" && !message.includes("not available")} className="mt-6 rounded-xl bg-teal-600 px-5 py-3 text-sm font-bold text-white disabled:opacity-60">{state === "joining" ? "Joining…" : state === "unavailable" ? "Video unavailable" : "Join video visit"}</button></div>}{state === "joined" && <div className="mt-6 grid gap-4 lg:grid-cols-2"><div className="relative aspect-video overflow-hidden rounded-3xl bg-slate-900"><video ref={remoteVideo} autoPlay playsInline className="h-full w-full object-cover" /><span className="absolute bottom-3 left-3 rounded-lg bg-slate-950/70 px-3 py-1.5 text-sm font-semibold text-white">{peerName}</span></div><div className="relative aspect-video overflow-hidden rounded-3xl bg-slate-900"><video ref={localVideo} autoPlay muted playsInline className="h-full w-full object-cover" /><span className="absolute bottom-3 left-3 rounded-lg bg-slate-950/70 px-3 py-1.5 text-sm font-semibold text-white">You</span></div><div className="lg:col-span-2 flex justify-center gap-3"><button onClick={toggleMic} className="rounded-2xl bg-white p-4 text-slate-700 shadow-sm" aria-label={micOn ? "Mute microphone" : "Turn microphone on"}>{micOn ? <Mic /> : <MicOff />}</button><button onClick={toggleCamera} className="rounded-2xl bg-white p-4 text-slate-700 shadow-sm" aria-label={cameraOn ? "Turn camera off" : "Turn camera on"}>{cameraOn ? <Video /> : <VideoOff />}</button><button onClick={leave} className="rounded-2xl bg-rose-600 p-4 text-white" aria-label="Leave video visit"><PhoneOff /></button></div></div>}</section></main>;
}
