"use client";

import { FormEvent, useEffect, useState } from "react";
import { AlertCircle, CheckCircle2 } from "lucide-react";
import { useAuthStore, UserProfile } from "@/store/useAuthStore";
import PortalShell from "@/components/PortalShell";

type FormData = Pick<UserProfile, "name" | "age" | "weight" | "height" | "gender" | "allergies" | "chronic_illnesses">;
export default function ProfilePage() {
  const { user, token, setAuth } = useAuthStore(); const [form, setForm] = useState<FormData>({ name: "", age: null, weight: null, height: null, gender: null, allergies: "", chronic_illnesses: "" }); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  useEffect(() => { if (user) setForm({ name: user.name || "", age: user.age ?? null, weight: user.weight ?? null, height: user.height ?? null, gender: user.gender ?? null, allergies: user.allergies || "", chronic_illnesses: user.chronic_illnesses || "" }); }, [user]);
  const update = (field: keyof FormData, value: string) => setForm((current) => ({ ...current, [field]: ["age", "weight", "height"].includes(field) ? (value === "" ? null : Number(value)) : value }));
  const save = async (event: FormEvent) => { event.preventDefault(); if (!user || !token) return; setSaving(true); setError(""); setMessage(""); try { const response = await fetch(`http://localhost:8100/api/v1/users/${user.id}`, { method: "PUT", headers: { "Content-Type": "application/json", Authorization: `Bearer ${token}` }, body: JSON.stringify(form) }); const updated = await response.json(); if (!response.ok) throw new Error(updated.detail || "We could not save your profile."); setAuth(token, { ...user, ...updated }); setMessage("Your profile has been saved."); } catch (err) { setError(err instanceof Error ? err.message : "We could not save your profile."); } finally { setSaving(false); } };
  return <PortalShell title="My profile" subtitle="Keep the details your doctor needs up to date"><form onSubmit={save} className="mx-auto max-w-3xl space-y-6 p-4 sm:p-6 lg:p-8"><section className="rounded-2xl border border-slate-200 bg-white p-5 sm:p-6"><h1 className="text-2xl font-bold">My profile</h1><p className="mt-1 text-sm text-slate-600">These details help your care team prepare for your visit.</p>{message && <p className="mt-5 flex items-center gap-2 rounded-xl bg-teal-50 p-3 text-sm text-teal-800"><CheckCircle2 className="h-4 w-4" />{message}</p>}{error && <p className="mt-5 flex items-center gap-2 rounded-xl bg-rose-50 p-3 text-sm text-rose-700"><AlertCircle className="h-4 w-4" />{error}</p>}<div className="mt-6 grid gap-4 sm:grid-cols-2"><Field label="Full name"><input value={form.name} onChange={(e) => update("name", e.target.value)} required /></Field><Field label="Email"><input value={user?.email || ""} disabled className="bg-slate-50 text-slate-500" /></Field></div></section><section className="rounded-2xl border border-slate-200 bg-white p-5 sm:p-6"><h2 className="text-lg font-bold">Health details</h2><p className="mt-1 text-sm text-slate-600">Only share information you are comfortable sharing with your doctor.</p><div className="mt-5 grid gap-4 sm:grid-cols-3"><Field label="Age"><input type="number" min="0" value={form.age ?? ""} onChange={(e) => update("age", e.target.value)} /></Field><Field label="Weight (kg)"><input type="number" min="0" value={form.weight ?? ""} onChange={(e) => update("weight", e.target.value)} /></Field><Field label="Height (cm)"><input type="number" min="0" value={form.height ?? ""} onChange={(e) => update("height", e.target.value)} /></Field></div><Field label="Gender" className="mt-4"><select value={form.gender || ""} onChange={(e) => update("gender", e.target.value)}><option value="">Prefer not to say</option><option>Female</option><option>Male</option><option>Other</option></select></Field><div className="mt-4 grid gap-4 sm:grid-cols-2"><Field label="Allergies"><textarea rows={4} value={form.allergies || ""} onChange={(e) => update("allergies", e.target.value)} placeholder="For example, penicillin or peanuts" /></Field><Field label="Ongoing health conditions"><textarea rows={4} value={form.chronic_illnesses || ""} onChange={(e) => update("chronic_illnesses", e.target.value)} placeholder="For example, asthma or diabetes" /></Field></div></section><button disabled={saving} className="rounded-xl bg-teal-600 px-5 py-3 text-sm font-bold text-white hover:bg-teal-700 disabled:opacity-60">{saving ? "Saving…" : "Save changes"}</button></form></PortalShell>;
}
function Field({ label, children, className = "" }: { label: string; children: React.ReactNode; className?: string }) { return <label className={`block text-sm font-semibold text-slate-700 ${className}`}>{label}<span className="mt-2 block [&_input]:w-full [&_input]:rounded-xl [&_input]:border [&_input]:border-slate-300 [&_input]:px-3 [&_input]:py-3 [&_select]:w-full [&_select]:rounded-xl [&_select]:border [&_select]:border-slate-300 [&_select]:px-3 [&_select]:py-3 [&_textarea]:w-full [&_textarea]:rounded-xl [&_textarea]:border [&_textarea]:border-slate-300 [&_textarea]:p-3">{children}</span></label>; }
