"""add_escalation_and_events

Revision ID: b46b27d35cb5
Revises: 90149d3eca01
Create Date: 2026-06-27 11:53:10.117906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b46b27d35cb5'
down_revision: Union[str, Sequence[str], None] = '90149d3eca01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('appointment_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # Adding Boolean requires_escalation to clinical_notes table with default 0 (False) to support SQLite constraints
    op.add_column('clinical_notes', sa.Column('requires_escalation', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clinical_notes', 'requires_escalation')
    op.drop_table('system_events')
    # ### end Alembic commands ###
